# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Use plugins instead of require
plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'

# Project-specific configurations
Style/Documentation:
  Enabled: false

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

# Fix the Thread department issue by using specific thread safety cops
# Instead of "Thread: Enabled: true", we need to enable specific cops
ThreadSafety/NewThread:
  Enabled: true

ThreadSafety/ClassInstanceVariable:
  Enabled: true

# Performance optimizations
Performance:
  Enabled: true

# RSpec-specific configurations
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

# Rails API-specific adjustments
Rails/HttpStatus:
  EnforcedStyle: symbolic

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
