# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.4
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set working directory
WORKDIR /rails

# Configure bundler
ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy entrypoint script
COPY docker-entrypoint.dev.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint.dev.sh
ENTRYPOINT ["docker-entrypoint.dev.sh"]

# Configure the main process to run when running the image
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
